# Copyright 2020-2023 The MathWorks, Inc.

# Composite Action to generate Code Coverage XML and Upload it
name: Generate Code Coverage XML
on: [push]

jobs:
    generate-code-coverage:
        runs-on: ubuntu-latest

        steps:
        - name: Set up Ruby
          uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
          with:
            ruby-version: '3.1'

        - name: Install Bashcov
          run: gem install bashcov

        - name: Run shell script tests
          run: |
            chmod +x tests/testing_shell.sh  # Make sure your test scripts are executable

        - name: Upload reports to Codecov
          uses: codecov/codecov-action@v2
