# Copyright 2020-2023 The MathWorks, Inc.

# Composite Action to generate Code Coverage XML and Upload it
name: Generate Code Coverage XML

on: [push]

jobs:
    run-unit-tests:
        runs-on: ubuntu-latest
        steps:
        - name: Set up Ruby
          uses: actions/setup-ruby@v1
          with:
            ruby-version: '2.7'

        - name: Install Ruby dependencies
          run: bundle update --bundler && bundle install

        - name: Run script
          run: |
            chmod +x tests/testing_shell.sh  # Make sure your test scripts are executable
            bashcov ./tests/testing_shell.sh

        - name: Upload reports to Codecov
          uses: codecov/codecov-action@v2
