name: Shell Script Tests with shunit2
on: [push]
  # workflow_dispatch:
  # workflow_call:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install shunit2
      run: |
        git clone https://github.com/kward/shunit2.git

    - name: Run shell script tests
      env:
        SHUNIT2_PATH: ${{ github.workspace }}/shunit2/shunit2
      run: |
        chmod +x tests/test_optional_user_command.sh  # Make sure your test scripts are executable
        sh ./tests/test_optional_user_command.sh