name: Shell Script Tests with shunit2
on: [push]
  # workflow_dispatch:
  # workflow_call:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # - name: Install shunit2
    #   run: |
    #     git clone https://github.com/kward/shunit2.git

    - name: Install BATS
      run: |
        git clone https://github.com/bats-core/bats-core.git
        cd bats-core
        sudo ./install.sh /usr/local

    - name: Run shell script unit tests
      # env:
      #   SHUNIT2_PATH: ${{ github.workspace }}/shunit2/shunit2
      working-directory: ${{ github.workspace }}/matlab-on-aws/tests
      run: |
        bats tests/test-check-profile.bats